export enum GoogleAddressType {
  STREET_ADDRESS = "street_address",
  STREET_NUMBER = "street_number",
  PREMISE = "premise",
  POINT_OF_INTEREST = "point_of_interest",
  ESTABLISHMENT = "establishment",
  ROUTE = "route",
  NEIGHBORHOOD = "neighborhood",
  SUBLOCALITY = "sublocality",
  SUBLOCALITY_LEVEL_1 = "sublocality_level_1",
  ADMINISTRATIVE_AREA_LEVEL_1 = "administrative_area_level_1",
  LOCALITY = "locality",
  ADMINISTRATIVE_AREA_LEVEL_2 = "administrative_area_level_2",
  COUNTRY = "country",
  POSTAL_CODE = "postal_code",
  POSTAL_CODE_PREFIX = "postal_code_prefix",
  POSTAL_CODE_SUFFIX = "postal_code_suffix",
  NATURAL_FEATURE = "natural_feature",
  ADMINISTRATIVE_AREA_LEVEL_3 = "administrative_area_level_3",
  ADMINISTRATIVE_AREA_LEVEL_4 = "administrative_area_level_4",
  ADMINISTRATIVE_AREA_LEVEL_5 = "administrative_area_level_5",
}
