export const SubCategoriesCodes = {
  Apartment: "AP",
  Townhouse: "TH",
  VillaCompound: "VC",
  Penthouse: "PH",
  HotelApartment: "HA",
  Building: "BL",
  Plot: "PL",
  Duplex: "DP",
  Villa: "VL",
  Floor: "FL",
  Studio: "ST",
  Other: "OT",
  Office: "OF",
  LabourCamp: "LC",
  Shop: "SH",
  Warehouse: "WH",
  IndustrialLand: "IL",
  BulkUnit: "BU",
  MixedUseLand: "MU",
  Showroom: "SR",
  Farm: "FM",
};
